//REGISTER USER

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "First_Name":"Amanda",
    "Last_Name": "Chepkoech",
    "Email": "amanda.chepkoech@thejitu.com",
    "Cohort_Number": "22",
    "Password": "amanda12"
}

###
//GET ONE USER

GET http://localhost:3000/auth/getUser/57726c7b-2c09-4aa3-9635-747ca8730a49
Content-Type: application/json

###
//UPDATE USER
POST  http://localhost:3000/auth/update/e233cfc4-a23e-4ab6-97cd-dcba5f61daab
Content-Type: application/json

{
    "First_Name":"Sharon",
    "Last_Name": "Cherotich",
    "Email": "sharon.cherotich@thejitu.com",
    "Cohort_Number": "22"
}


###
//DELETE USER

DELETE http://localhost:3000/auth/delete/675b5d93-1868-4580-9884-331ca56703ee
Content-Type: application/json

###
//GET ALL USERS
GET http://localhost:3000/auth/allUsers
Content-Type: application/json