POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  
  "fullName": "Sharon",
  "email": "sharon@gmail.com",
  "phoneNumber": "0712345567",
  "password": "test12"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "sharon@gmail.com",
  "password": "test12"
}

###
